version: '2.3'

services:
  flask1:    # flask server for covid19 service web pages and APIs, with backend tensorflow servering
    build:
      context: ./covid19
    image: ai-service-flask:0.1.0
    hostname: flask
    restart: on-failure
    ports:
      - 8051:5000 # tensorflow servring port
    volumes:
      - ./covid19:/app  # tf2 serving convention

  flask2:    # flask server for covid19 service web pages and APIs, with backend tensorflow servering
    build:
      context: ./covid19
    image: ai-service-flask:0.1.0
    hostname: flask
    restart: on-failure
    ports:
      - 8052:5000 # tensorflow servring port
    volumes:
      - ./covid19:/app  # tf2 serving convention

  flask3:    # flask server for covid19 service web pages and APIs, with backend tensorflow servering
    build:
      context: ./covid19
    image: ai-service-flask:0.1.0
    hostname: flask
    restart: on-failure
    ports:
      - 8053:5000 # tensorflow servring port
    volumes:
      - ./covid19:/app  # tf2 serving convention

  lb:
    build:
      context: ./haproxy
    image: 'haproxy:0.0.1'
    volumes:
      - ./haproxy:/haproxy-override
    links:
      - flask1
      - flask2
      - flask3
    ports:
      - 8088:8088
    expose:
      - 8088
